### PR TITLE
Added tests for EditItem, and cleaned up other code

### PR DESCRIPTION
**Pull request by deonjo**

### CODE REVIEW

**Comment by jeffchiucp** [comment]
@gabekoo  @deonjo  
How Do you run the test via enzyme? 
 Can you share the terminal commands?
Can you provide the result of the test through screenshot?

**Comment by jeffchiucp** [comment]
@deonjo  Maybe we can use a CI tool like Now.json so it automatically deployed ?
Do you want me to add that environment?
It should be pretty quick to set up the Zeit.io Now since we already have now.json file?

**Comment by deonjo** [comment]
you just use the command `npm run test`
I don't think we should automatically deploy code...

**Comment by jeffchiucp** [comment]
nice. I just ran the test. Here's a screenshot
Screen Shot 2019-05-29 at 9 40 14 AM

**Pull request merged**
